In [10]:
import numpy as np
from matplotlib import pyplot as plt
import random

In [112]:
def randomGraph(n, p):
    ''' 
    Returns the numpy matrix associated with a random graph on n vertices,
    where each pair of vertices has probability p of being connected.
    '''
    matrix = np.zeros((n, n))
    for i in range(n):
        for j in range(i):
            coin = random.random()
            if coin < p:
                matrix[(i, j)] = 1
                matrix[(j, i)] = 1
    return matrix

def dRegularCycles(n, d):
    ''' 
    Given n and d (which has d + 1|n), returns a "very cliquey" graph, defined below.

    The vibe here is to make a graph which is d regular but expands very poorly. To force this,
    we'll divide the the vertex set into partitions of d + 1 vertices. Then each of these sub vertex
    sets will be fully connected and form a clique.

    Each vertex is part of exactly one d + 1 connected clique, and so has out degree d.
    '''

    numVertexSets = int(n / (d + 1))
    result = np.zeros((n, n))

    # d+1 x d+1 matrix for the connected cliques
    fullyConnected = np.ones((d + 1, d + 1))
    np.fill_diagonal(fullyConnected, 0)

    # Fill adjacency matrix with the connected cliques
    for i in range(numVertexSets):
        startIndex = i*(d + 1)
        result[startIndex:(startIndex + d + 1), startIndex:(startIndex + d + 1)] = fullyConnected

    return result



def maxEigVal(matrix):
    ''' 
    Given the adjacency matrix of an undirected graph, returns the largest eigenvalue
    '''
    eigVals = np.linalg.eigvalsh(matrix)
    return max(eigVals)
    

In [113]:
matrix = dRegularCycles(10, 3)
print(matrix)

[[0. 1. 1. 1. 0. 0. 0. 0. 1. 1.]
 [1. 0. 1. 1. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 1. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]]
